%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\20192420\Documents\Q3 Y2\data exp 2\TestE10_half_load_2.txt
%
% Auto-generated by MATLAB on 03-Mar-2021 09:49:14

%% Setup the Import Options (E0)
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [21201, 25200];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["E0", "E1", "E2"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TestE0halfload2 = readtable("C:\Users\20193197\OneDrive - TU Eindhoven\University\4GB10\raw_data_exp2\TestE0_half_load_2.txt", opts);

t_hl_0            = TestE0halfload2.E0;
puls_sens_hl_0  = TestE0halfload2.E1;
pres_sens_hl_0 = TestE0halfload2.E2;

%% E5
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [21651, 25650];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["E0", "E1", "E2"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

TestE5halfload2 = readtable("C:\Users\20193197\OneDrive - TU Eindhoven\University\4GB10\raw_data_exp2\TestE5_half_load_2.txt", opts);

t_hl_5            = TestE5halfload2.E0;
puls_sens_hl_5  = TestE5halfload2.E1;
pres_sens_hl_5 = TestE5halfload2.E2;

%% E10
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [18101, 22100];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["E0", "E1", "E2"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
TestE10halfload2 = readtable("C:\Users\20193197\OneDrive - TU Eindhoven\University\4GB10\raw_data_exp2\TestE10_half_load_2.txt", opts);

t_hl_10            = TestE10halfload2.E0;
puls_sens_hl_10  = TestE10halfload2.E1;
pres_sens_hl_10 = TestE10halfload2.E2;

%% E15
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [17451, 21450];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["E0", "E1", "E2"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
TestE15halfload2 = readtable("C:\Users\20193197\OneDrive - TU Eindhoven\University\4GB10\raw_data_exp2\TestE15_half_load_2.txt", opts);

t_hl_15            = TestE15halfload2.E0;
puls_sens_hl_15  = TestE15halfload2.E1;
pres_sens_hl_15 = TestE15halfload2.E2;
%%
pressure_relative_hl_0  = (pres_sens_hl_0 -(0.115*5))/(0.00385*5*4); %formula from Canvas 
pressure_hl_0 = pressure_relative_hl_0 - 7.2  % ?? estimated (relative sensor)

pressure_relative_hl_5  = (pres_sens_hl_5 -(0.115*5))/(0.00385*5*4); %formula from Canvas 
pressure_hl_5 = pressure_relative_hl_5 - 8.8 % ?? estimated (relative sensor)

pressure_relative_hl_10  = (pres_sens_hl_10 -(0.115*5))/(0.00385*5*4); %formula from Canvas 
pressure_hl_10 = pressure_relative_hl_10 - 10.2   % ?? estimated (relative sensor)

pressure_relative_hl_15  = (pres_sens_hl_15 -(0.115*5))/(0.00385*5*4); %formula from Canvas 
pressure_hl_15 = pressure_relative_hl_15 - 10 % ?? estimated (relative sensor)

phi_speed = 18000*t_hl_0 
phi = phi_speed %

% figure()
% plot(phi, pressure_hl)

%% Multiple figures
% Create plots

% figure('Name','Half load')
% subplot(1,4,1)
% plot(phi, pressure_hl_0)
% title('E0 half load')
% 
% xlabel('Crank Angle')
% ylabel('Pressure (bar)')
% subplot(1,4,2)
% plot(phi, pressure_hl_5)
% title('E5 half load')
% 
% xlabel('Crank Angle')
% ylabel('Pressure (bar)')
% subplot(1,4,3)
% plot(phi, pressure_hl_10)
% title('E10 half load')
% 
% xlabel('Crank Angle')
% ylabel('Pressure (bar)')
% subplot(1,4,4)
% plot(phi, pressure_hl_15)
% title('E15 half load')
% 
% xlabel('Crank Angle')
% ylabel('Pressure (bar)')

%% One figure has all

figure()
plot(phi, pressure_hl_0)
hold on
plot(phi, pressure_hl_5)
hold on
plot(phi, pressure_hl_10)
hold on
plot(phi, pressure_hl_15)
legend('E0', 'E5', 'E10', 'E15')
xlabel('Crank Angle [phi]')
ylabel('Pressure [bar]')
title('Half Load')

%%
%

a = 0.027; %radius (equal to stroke/2)
B = 0.068; %diameter of bore
L = 0.085; %length of rod
Vc = 5/1000000; %deathvolume or clearance volume, estimated value %aanpassen

s = a*cosd(phi) + (L.^2 + (a.^2)*(sind(phi)).^2).^(0.5); %explained in ssa
Volume = (((pi)*B.^2)/(4))*(L + a - s)+ Vc; %explained in ssa

% figure('Name','half load')
% subplot(2,2,1)
% plot(Volume, pressure_hl_0)
% title('E0 half load')
% 
% xlim([0,2.1e-4])
% xlabel('Volume')
% ylabel('Pressure (bar)')
% subplot(2,2,2)
% plot(Volume, pressure_hl_5)
% title('E5 half load')
% 
% xlim([0,2.1e-4])
% xlabel('Volume')
% ylabel('Pressure (bar)')
% subplot(2,2,3)
% plot(Volume, pressure_hl_10)
% title('E10 half load')
% 
% xlim([0,2.1e-4])
% xlabel('Volume')
% ylabel('Pressure (bar)')
% subplot(2,2,4)
% plot(Volume, pressure_hl_15)
% title('E15 half load')
% 
% xlim([0,2.1e-4])
% xlabel('Volume')
% ylabel('Pressure (bar)')

%% One figure has all pv

figure()
plot(Volume, pressure_hl_0)
hold on
plot(Volume, pressure_hl_5)
hold on
plot(Volume, pressure_hl_10)
hold on
plot(Volume, pressure_hl_15)
legend('E0', 'E5', 'E10', 'E15')
xlabel('Volume [m^3]')
ylabel('Pressure [bar]')
title('Half Load PV')

%% Clear temporary variables
clear opts